url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Tom Gilbertson's Lab" # the name of your site, e.g. ACME Corp.
description: "Investigating Structureâ€“Function Drivers of Apathy"
